### PR TITLE
save_audio checkbox

### PR DESCRIPTION
**Pull request by artjomsR**
Sometimes the audio from forvo is bad quality / of a wrong accent / you just plain don't like it. This PR adds a button that removes the audio from the current card so it's not saved. This saves the hassle of saving the card and then deleting audio manually from the freshly created card.

I've also moved the image clear call to the same block so it behaves consistently, fixed a few text descriptions for consistency and added "define on double click" to vertical layout which I missed last time.

image
image

### CODE REVIEW

**Comment by 1over137** [comment]
The idea is fine but I would prefer it to be the opposite way. Add a pushbutton instead of the checkbox, that says "Discard audio", and also make that clear the pronunciation selector.  It should act as if no audio is found.

**Comment by artjomsR** [comment]
Ok no problem, makes sense, I'll update it

**Comment by 1over137** [comment]
Also regarding layout: Please make sure the button is also accessible when using the horizontal layout (defined in setupWidgetsH)

**Comment by artjomsR** [comment]
Updated code & description

**Pull request merged**
