### PR TITLE
Non-blocking audio; typehints; minor func decoupling

### PR DESCRIPTION
**Pull request by Blackdeer1524**

### CODE REVIEW

**Comment by 1over137** [comment]
IIRC blocking=False is not supported in some platforms.
Also I already bundled a version of playsound.py in the repo to avoid the need to have a hard non-latest dependency (1.3.0 would not work).

**Comment by Blackdeer1524** [comment]
I don't quite see why it is a problem to have `playsound` as a non-latest dependency. Could you explaint?

**Comment by 1over137** [comment]
Did you test if your modified setupWidgetsV and setupWidgetsH would reload the widgets when dictionary 2 is turned on or off?

**Comment by Blackdeer1524** [comment]
No, my bad. Everything should be file now.

**Comment by 1over137** [comment]
I fixed that. Note that `typing_extensions` is an external package, so it needs to be added to requirements.txt and setup.cfg.

**Pull request merged**
