### PR TITLE
Added View Note  and View Last Note buttons, lookup on hover

### PR DESCRIPTION
**Pull request by PIPPOHSIOS**
These are the main features that I added to VocabSieve:
- View Note button lets you view the note on Anki Browser for a given target word when it's looked up, moreover the user can understand when a word is already in the sentence mining deck since the button for adding the note would be grayed out. 
- View Last Note lets you view the last added note on Anki Browser, it could be useful if you mistakenly added the note and you want to delete it or modify something. 
- Added the possibility to look up words hovering over them, even without having the window focused. In my opinion, it's a powerful feature because makes the lookup process a little bit faster and more convenient, especially when the user relies heavily on keyboard (with the left hand) and on software that copy text automatically like mpvacious.

I also fixed some various issues and problems that I found when using the software. The main fixes are:
- Fixed tooltip on dark theme
- Changing theme does not reset the accent colour
- Enabled HiDpi with qdarktheme, Text Scaling setting now works properly
- HTML notes should be added to Anki without throwing error. Before this fix sometimes (to me it was always the case in v0.11) notes wouldn't be added, throwing an error saying that `self.original` wasn't a property of `MultiDefinitionWidget`
- Improved the Frequency Display, essentially I made the code ready to be modified easily for future changes and additions

Unfortunately I don't know if many of these fixes actually work on other systems, because currently I don't have to possibility to do other tests. I've tested everything on a Windows 11 laptop with scaling enabled.

### CODE REVIEW

**Comment by artjomsR** [comment]
I was getting `ModuleNotFoundError: No module named 'pynput'` on this PR - I think you need to add it to requirements.txt

**Comment by PIPPOHSIOS** [comment]
I added pynput to requirements.txt, now it should work.

**Comment by 1over137** [comment]
I think pynput wouldn't work on Linux with Wayland, but there's not much we can really do at this point, so I don't mind. Note that you need to add the dependency to setup.cfg too for pip to properly resolve dependencies on PyPI. Can you elaborate on how the lookup on hover thing is supposed to work? Are you supposed to hover over an inactive VocabSieve window? Does this interfere with when the window is in focus? My usual environment is Hyprland where focus always follows mouse so I'll need to find some other way to test this.

**Comment by PIPPOHSIOS** [comment]
Here is a recording of how the features work.

https://github.com/FreeLanguageTools/vocabsieve/assets/40296512/278ef5c6-b787-4e69-963c-44abd8cc19d7

You can hover over a word while holding down the shift key and VocabSieve will find a definition for it regardless of the focus of the window.
For a word already present in your Anki sentence mining deck (in the case of the video the word is **собственно**) the Add Note will be grayed out and instead the View Note button will be enabled. This could also be used as a visual clue to understand whether or not the card is already added on the deck. In fact, if the word is not present in your sentence mining deck, the Add Note button will be enabled and the View Note one will be disabled.
Finally the View Last Note button makes you see the last added note with VocabSieve (in this case the last word added was **первый**).

If you have further questions regarding the features of the various code changes that I made, please feel free to ask.

**Comment by 1over137** [comment]
Cool!
"View last note" is nice to have, but I have some doubts about the duplicate handling here. Recent versions of Anki allow adding duplicates actually and AnkiConnect iirc has a way to add duplicates, so maybe a better way of doing this would be making a popup dialog when user attempts to add to ask whether to add anyways. https://github.com/FreeLanguageTools/vocabsieve/issues/122 this seems to be a somewhat desirable feature to have.

**Comment by 1over137** [comment]
This is what it looks like now (window title is "Note already exists"). The user can decide whether to still add if the note is a duplicate
I removed the "view note" button for now, but maybe I should actually implement that into the dialog (3 buttons, OK, cancel, view)

**Comment by PIPPOHSIOS** [comment]
I think that adding duplicates can be really beneficial as there are many words whose meaning can change completely based on the context.
The main reason I added the "view note" button is because sometimes I'm not sure whether or not I added a word on my deck. Graying out the "add note" button gives me that visual clue and saves me many clicks, interrupting my immersion less abruptly.
I don't know if that's viable, but we can use the status bar to notify the user of the already present note for the selected word.
Regarding the note viewer widget, I think that could be really useful especially if you have duplicate notes. Instead of printing the content, wouldn't it be easier to just let the notes pop up on Anki browser? Otherwise we can just let the user choose what it wants, whether printing them on a messagebox, or opening them on Anki. Let me know what do you think about that!

**Comment by 1over137** [comment]
A few thoughts here:
1. Using the looked up word isn't really foolproof because it's the content of the word field that matters, not the word being looked up.
2. You shouldn't gray out the add note field because although the default settings won't allow it, the user can alternatively select the sentence to be the first field so there may not be a duplicate in the first place. This is dependent on the user's note type. The current default note type have word as first field, but the user can change that or use their own type, which is a supported use case.
3. There is already an indicator of how many cards you've added for a word to the right of the frequency display widget, though perhaps a bit non obvious: 
image
The "T" there means there is one mature card with the word being in target field and the "C" means there is one mature card with the word being in the context field. The mapping is defined in the "Match Fields" dialog of the Tracking tab in the config, called `fieldmap` in the code stored as a json. You can hover on the widget to see the details.

**Comment by 1over137** [comment]
image
Now it looks like this

**Comment by PIPPOHSIOS** [comment]
My bad, somehow I completely overlooked the frequency display widget in this new version.

How would you go about seeing multiple duplicate notes? Do you still think that some kind of view note widget should be added or you can just view all the note(s) using the dialog?

This is some kind of demo that I made on the fly.
image
Don't mind the last creation time, as I just made this changes as examples.

image
It's important to mention the fact that I changed the `find_query` and it looks like this `"deck:{deck_name} \"{target_word_field}:*{word}*\"`. As the Anki manual states, limiting the field requires an '_exact match_' by default. So to look for the word in the field you have to surround it with asterisks. In fact, due to the way I handled my duplicate notes, the frequency widget only showed me the word "наречие" as a context word and not as a target one.
image

**Comment by 1over137** [comment]
It should be an exact match, otherwise ходить will match происходить, for example. You should just fix your duplicate notes. I think I'll need to make it more flexible w.r.t. different first fields though, such as sentence. Also Anki duplicate is not limited by decks, so it should search for all decks with the same note type I think.

**Comment by PIPPOHSIOS** [comment]
I know the pull request is closed, but for some reason using `self.original` in the display_mode HTML handling throws me this error when trying to create a card:

> Traceback (most recent call last):
>   File "C:\Users\\-\Documents\source\vocabsieve\vocabsieve\main.py", line 856, in createNote
>     definition1=self.definition.process_defi_anki(),
>   File "C:\Users\\-\Documents\source\vocabsieve\vocabsieve\ui\multi_definition_widget.py", line 175, in process_defi_anki
>     return self.original # no editing, just send the original html, using toHtml will change the html
> AttributeError: 'MultiDefinitionWidget' object has no attribute 'original'

Unfortunately, I haven't found out why this happens and I just thrown `self.toHtml()` as a quick fix.

**Comment by 1over137** [comment]
Ah, I must have forgotten to reimplement that, thanks for the reminder.

**Comment by 1over137** [comment]
hi, I've been wondering, have you considered using QGuiApplication.keyboardModifiers() [doc](https://doc.qt.io/qtforpython-5/PySide2/QtGui/QGuiApplication.html#PySide2.QtGui.PySide2.QtGui.QGuiApplication.keyboardModifiers) to implement this hovering feature or is pynput necessary?

**Comment by PIPPOHSIOS** [comment]
Hello. As far as I know, Qt wants the window focused in order to process a keyboard related event. Then after reading on a [post](https://forum.qt.io/post/425341) on the Qt forum that you actually need to use native API, I kind of just gave up and used pynput. There is also another python library named [keyboard](https://pypi.org/project/keyboard/) that seems to do the same job as pynput, and it also seems to support Linux. I'll test something out and let you know.

**Comment by PIPPOHSIOS** [comment]
So I substituted pynput with the keyboard library and it just works the same, at least on Windows. I read on the github page of the library that it supports both Linux (apparently on both Wayland and XOrg) and OS X. Though for the first one it only works with sudo privileges and the support for the latter is still experimental. I don't think it's really worth it to use this library, especially because it's not currently maintained, but I pushed the changes nonetheless so that you can test them for yourself.

**Comment by 1over137** [comment]
Cool, thanks for the comment. It's not that big of a problem, but I noticed that pynput on wayland doesn't work even with the window focused, which I assume it would with Qt's own support. On my wayland compositor (Hyprland) focus follows mouse so any window under mouse is always focused, without me needing to click it.

**Pull request merged**
